name: Build Aseprite

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          choco install ninja cmake git python openssl --no-progress -y

      - name: Setup MSVC
        uses: microsoft/setup-msbuild@v2

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake -G Ninja ^
            -DCMAKE_BUILD_TYPE=RelWithDebInfo ^
            -DLAF_BACKEND=skia ^
            -DSKIA_DIR=..\skia ^
            -DSKIA_LIBRARY_DIR=..\skia\out\Release-x64 ^
            -DSKIA_LIBRARY=..\skia\out\Release-x64\skia.lib ^
            -DOPENSSL_ROOT_DIR="C:\Program Files\OpenSSL-Win64" ..

      - name: Build Aseprite
        run: |
          cd build
          ninja

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-build
          path: build\bin
